version: '3.8'
services:
    db:
       container_name: postgres
       build: 
           context: .
           dockerfile: ./docker/postgres
       image: wxn_postgres
       restart: always
       env_file:
          - .env
       environment:
           POSTGRES_USER: ${POSTGRES_USER}
           POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
           POSTGRES_DB: ${POSTGRES_DB}
       ports:
          - 5434:5432
       volumes:
          - ./docker/postgres/data:/var/lib/postgresql/data
          - ./docker/postgres/config:/etc/postgresql  

volumes:
    db:          
